// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not configured — run flutterfire configure',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not configured — run flutterfire configure',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not configured — run flutterfire configure',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not configured — run flutterfire configure',
        );
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-G22XREuMK-z-WYoz27WDUJGrFQAaGZY',
    appId: '1:493110256900:android:759a954419dcffef569c51',
    messagingSenderId: '493110256900',
    projectId: 'actechs-d415e',
    storageBucket: 'actechs-d415e.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETPeEA7INduyW_3mo7pvCJ7QOPaaGrWw',
    appId: '1:493110256900:web:8aa96a3450fad9c1569c51',
    messagingSenderId: '493110256900',
    projectId: 'actechs-d415e',
    authDomain: 'actechs-d415e.firebaseapp.com',
    storageBucket: 'actechs-d415e.firebasestorage.app',
  );
}
